### ISSUE TITLE
NetflowV9: Kafka server message too large 

### ISSUE THREAD

**Issue by JPercivall** [VerizonDigital/vflow#40]
I'm running the 0.4.1 vFlow docker image and pushing to a Kafka instance within the same docker network that was created using docker-compose. I can run fine under very low throughput but when I attempt to increase it (using the exact same netflow message) I run into the issue that vFlow fails to push to Kafka because the message was too large.

TLDR: I believe I'm running into this issue: https://github.com/Shopify/sarama/issues/959 and can't use the proposed solution.

## Setup:
My docker compose yaml file.
```
version: '2'

services:
  zookeeper:
    image: zookeeper:3.4.11
    restart: always
    container_name: 'zookeeper'
    hostname: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:0.11.0.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_CREATE_TOPICS: "vflow.netflow9:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  vflow:
    image: 'mehrdadrad/vflow:v0.4.1'
    container_name: 'vflow'
    hostname: 'vflow'
    volumes:
      - ./vflow/:/etc/vflow/
    ports:
      - "4729:4729/udp" # netflowV9
      # - "4739:4739/udp" # ipfix
      # - "6343:6343/udp" # sflow
      - "9081:8081" # stats
    depends_on:
      - kafka
```
Within the "./vflow" directory I have two input config files:

vflow.conf:
```
ipfix-enabled: false
ipfix-workers: 0

sflow-enabled: false
sflow-workers: 0

netflow-enabled: false
netflow9-workers: 50

log-file: /etc/vflow/vflow.log
mq-name: kafka
mq-config-file: /etc/vflow/mq.conf
ipfix-tpl-cache-file: /usr/local/vflow/vflow.templates
```

 mq.conf:
```
brokers:
    - kafka:9092
retry-max: 1
retry-backoff: 30
```

## Starting up:
I am able to run all three services and produce/consume events from Kafka outside of vFlow without issue. vFlow starts up and lists the following in the logs:

```
[vflow] 2017/11/30 21:01:09 ipfix disabled
[vflow] 2017/11/30 21:01:10 vFlow has been shutdown
[vflow] 2017/11/30 21:01:10 netflow v9 has been shutdown
[vflow] 2017/11/30 21:01:20 Welcome to vFlow v.unknown Apache License 2.0
[vflow] 2017/11/30 21:01:20 Copyright (C) 2017 Verizon. github.com/VerizonDigital/vflow
[vflow] 2017/11/30 21:01:20 starting stats web server ...
[vflow] 2017/11/30 21:01:20 sflow has been disabled
[vflow] 2017/11/30 21:01:20 ipfix has been disabled
[vflow] 2017/11/30 21:01:20 netflow v9 is running (UDP: listening on [::]:4729 workers#: 50)
[vflow] 2017/11/30 21:01:20 start producer: Kafka, brokers: [kafka:9092], topic: vflow.netflow9
```

## The issue:
Sending NetflowV9 works as expected just a few messages but when I start increasing the number of messages I send it I see the following message repeated over and over: 

```
[vflow] 2017/11/30 22:30:37 kafka: Failed to produce message to topic vflow.netflow9: kafka server: Message was too large, server rejected it to avoid allocation error.
```

As stated before, I believe this is because of a issue identified in this thread: https://github.com/Shopify/sarama/issues/959

Essentially Kafka changed what "max.message.bytes" means with version 0.11 leading to issues Sarama has set as default. Since I can't (as far as I know) configure "sarama.MaxRequestSize" within the vFlow Kafka producer, it will always hit this with Kafka v0.11 on any normal throughput.

## Proposed resolution:
Offer more configurations around the Kafka producer, particularly in relation to Sarama so that "sarama.MaxRequestSize" can be reduced to 1000000.

**Comment by JPercivall** [comment]
Rolling back to Kafka version 0.10.2.1 appears to work. Which is in line with the suggested root problem.

Relevant updated docker-compose file:
```
  kafka:
    image: wurstmeister/kafka:0.10.2.1
    container_name: 'kafka'
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_CREATE_TOPICS: "vflow.netflow9:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
```
